corpus_id: 173
customer_id: 1526022105

app_title: "Ask HBS"
search_title: "Ask HBS"
search_description: "Harvard Business School"

summary_default_language: "en"
summary_num_sentences: 3
summary_num_results: 5
rerank: true

enable_source_filters: False
source: ""
