[workplace]
api_key="zwt_WvU_2cKdquQi1ufzaeMP0avkmp9z2cFn74bXuA"
google_client_id="478086537153-ld7poe6b4hhvmppuo1ge03g1p2pqi5m1.apps.googleusercontent.com"

[staging]
api_key="zwt_0L3mT2jHIIdYfHe7-be2is-Fkpnhzm0g1uCM-A"

[finance]
api_key="zwt_WvU_2eMx2FbH9OlzrYmTAIaJB2BjUuapsg1Qjw"

[finsearch]
api_key="zwt_WvU_2eOwyAYrq5wGNwewfmRkqvdMEMp9HiTdDw"

[pg]
api_key="zwt_RbZfGTjyuivpd7RHRObu0dTlIYP2HT91BGerpw"

[langchain]
api_key="zwt_WvU_2fcpFwp-KcJ_Ffqc9UD4gAJAzU-NIRmP4A"

[wikipedia]
api_key="zwt_WvU_2fEhAj0-zXHNk8UUlPdmM8vdmwlLhvHybw"

[personal]
api_key="zwt_RbZfGR8K8In1FWplNR1YbaU-dfK4jXeAtUX0Sw"

[lethain]
api_key="zwt_WvU_2eQPaof5v7SS_W6q0wQJx-376NybbAhLPA"

[transformers]
api_key="zwt_RbZfGT-7ePDKGnri0ujVgJ1YixiLxkas-2zBFA"

[sf]
api_key="zwt_RbZfGWGQmVJsjaGEG_9dxZXpFFfOVppRk-B6bQ"

[news]
api_key="zwt_WvU_2egiMNzLJ3mJAUAbXroSAK94IFk7ClZXHg"

[huggingface]
api_key="zwt_WvU_2eKjAgzHDy9ObdOng7bnRVT5bdaY3JTZSw"

