corpus_id: "161"
customer_id: 1526022105

app_title: "Ask Finance"
search_description: "Search financial data from 2015-2023"
search_logo_src: "images/financial_answers_logo.png"
search_logo_alt: "Finance Answers logo"
search_logo_height: "20"
