corpus_id: 169
customer_id: 1526022105

app_title: "Yelp reviews"
search_title: "Ask Yelp"
search_description: "Restaurants in St. Louis"

summary_default_language: "en"
summary_num_sentences: 2
summary_num_results: 5

enable_source_filters: False
source: ""
