corpus_id: 166
customer_id: 1526022105

app_title: "Legal Aid Illinois"
search_title: "Legal Aid Illinois"
search_description: "Based on www.illinoislegalaid.org"

enable_source_filters: False
source: ""
